name: "BUD Portal"
description: "BUD - Business Utility Dashboard"
url: "https://www.chilldivision.co.nz"
version: "0.15.0"
slug: "bud_addon"
panel_icon: mdi:truck-delivery
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 8420

map:
  - type: addon_config
    read_only: False
    path: /bud_config
